### ISSUE TITLE
Example integration with Prettier with Twig melody plugin

### ISSUE THREAD

**Issue by webrgp** [rholdos/vscode-twig-language-support#1]
First: great job!

I am having a hard time setting up this extension to work with Prettier with Twig melody plugin. Can you post an example? Thanks!

**Comment by rholdos** [comment]
Hey @webrgp, appreciated!

Sure, I've put together another repository with the plugin files wrapped up for easier installation, [check here](https://github.com/rholdos/prettier-plugin-twig).

My setup includes:
1. [Prettier](https://prettier.io) and [Twig plugin](https://github.com/rholdos/prettier-plugin-twig) (mentioned above) installed globally.
2. [Prettier extension](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) installed in VS Code, with the following settings (OSX paths):

<pre>
  // path to global package
  "prettier.prettierPath": "~/.nvm/versions/node/v16.13.0/lib/node_modules/prettier",

  // set prettier as default formatter for .twig files
  "[twig]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }

  // and I keep my prettier options in root config file
  // but I guess options defined in vscode's settings will work too
  "prettier.requireConfig": true,
  "prettier.configPath": "~/.prettierrc"
</pre>

That's it.  
Hope this helps. Feel free to continue this thread in case this won't work for you.
