### ISSUE TITLE
Typo in snippets for block and apply tags

### ISSUE THREAD

**Issue by mhlozek** [rholdos/vscode-twig-language-support#3]
When I use `block` snippet I get a code:

```
{% block 'name' %}

{% endblock 'name' %}
```
I think there should be no quotation marks around block name. 

The same problem could at `apply` tag.

Could you add endblock and endembed snippet please?

**Comment by rholdos** [comment]
Thanks for opening the issue.

1. Snippets for `block` and `apply` tags are now fixed.
2. Also added snippets for closing tags, including `endblock` and `endembed`.

Check out new version `1.0.1`.

**Comment by mhlozek** [comment]
Great! Thank you very much.
